"""change word model to having only kana field

Revision ID: 2430a5609daf
Revises: 73c59ce72cce
Create Date: 2025-03-26 15:28:22.717099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2430a5609daf'
down_revision: Union[str, None] = '73c59ce72cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('kana', sa.String(), nullable=False))
    op.drop_constraint('uq_word_hiragana', 'word', type_='unique')
    op.create_unique_constraint(op.f('uq_word_kana_translation'), 'word', ['kana', 'translation'])
    op.drop_column('word', 'hiragana')
    op.drop_column('word', 'katakana')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('katakana', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('word', sa.Column('hiragana', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_word_kana_translation'), 'word', type_='unique')
    op.create_unique_constraint('uq_word_hiragana', 'word', ['hiragana'])
    op.drop_column('word', 'kana')
    # ### end Alembic commands ###
